# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "Animal Legs Eval"

prompts:
  - prompts.py:simple_prompt
  - prompts.py:better_prompt
  - prompts.py:chain_of_thought_prompt
  

providers:
  # - "anthropic:messages:claude-opus-4-5-20251101"
  - "anthropic:messages:claude-sonnet-4-5-20250929"
  # - "anthropic:messages:claude-opus-4-1-20250805"
  # - "anthropic:messages:claude-3-7-sonnet-20250219"
  - "anthropic:messages:claude-3-haiku-20240307"
  

tests: animal_legs_tests.csv
 
defaultTest:
  options:
    transform: file://transform.py