# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: 'Summarization Evaluation'

prompts:
  - prompts.py:basic_summarize
  - prompts.py:better_summarize
  - prompts.py:best_summarize

providers:
  # - "anthropic:messages:claude-opus-4-5-20251101"
  - "anthropic:messages:claude-sonnet-4-5-20250929"
  # - "anthropic:messages:claude-opus-4-1-20250805"
  # - "anthropic:messages:claude-3-7-sonnet-20250219"
  
tests:
  - vars:
      article: file://articles/article1_JP.txt
  - vars:
      article: file://articles/article2_JP.txt
  - vars:
      article: file://articles/article3_JP.txt
  - vars:
      article: file://articles/article4_JP.txt
  - vars:
      article: file://articles/article5_JP.txt
  - vars:
      article: file://articles/article6_JP.txt
  - vars:
      article: file://articles/article7_JP.txt
  - vars:
      article: file://articles/article8_JP.txt

defaultTest:
  assert:
    - type: python
      value: file://custom_llm_eval.py
